name: Daily Update

on:
  push:
  schedule:
    - cron: "45 8 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Get source
        uses: actions/checkout@v2

      - name: Get Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/Hydrogen'

      - id: Update
        run: node update.mjs

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: Update README.md"
          add: 'profile README.md'
